version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - amintahlil-network
    restart: always
    command: redis-server --appendonly yes
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - amintahlil-network

  api:
    build: 
      context: ./backend
    ports:
      - "5000:80"
    depends_on:
      - jaeger
      - redis
    environment:
      - Jaeger__BaseUrl=http://jaeger:16686/api/traces
      - Jaeger__TimeoutSeconds=15
      - Features__EnableServiceMap=true
      - Features__EnableExport=true
      - Features__EnableNotifications=true
      - Redis__ConnectionString=redis:6379
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - amintahlil-network

  ui:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - amintahlil-network

networks:
  amintahlil-network:
    driver: bridge

volumes:
  redis-data:
